modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/Kir-Antipov/sync-fabric/issues"

[properties]
"connector:placeholder" = true

[[mods]]
modId = "sync"
version = "${version}"
displayName = "Sync (Fabric)"
description = "One mind. Many bodies."
logoFile = "assets/sync/icon.png"
logoBlur = false
authors = "Kir_Antipov, skycatminepokie, cassiancc"
displayURL = "https://github.com/Kir-Antipov/sync-fabric"

[[dependencies.sync]]
modId = "minecraft"
versionRange = "[1.21.1]"

[[dependencies.sync]]
modId = "connector"

[[dependencies.sync]]
modId = "fabric_api"